<?php

namespace Core\Views;

use App\App;
use App\Users\User;
use Core\View;

class Navigation extends View
{
    public function __construct($data = [])
    {
        $user = App::$session->getUser();
        if ($user) {
            switch ($user->getRole()) {
                case User::ROLE_USER:
                    $data = $this->getUserNavigation();
                    break;
                case User::ROLE_ADMIN:
                    $data = $this->getAdminNavigation();
                    break;
            }
        } else {
            $data = $this->getAnonymousNavigation();
        }
        parent::__construct($data);
    }

    public function render(string $template_path = ROOT . '/app/templates/nav.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

    public function getUserNavigation()
    {
        return [
            [
                'link' => '/cart',
                'name' => 'Cart'
            ],
            [
                'link' => '/orders/',
                'name' => 'Orders'
            ],
            [
                'link' => '/',
                'name' => 'Catalog'
            ],
            [
                'link' => '/logout',
                'name' => 'Log Out'
            ]
        ];
    }

    public function getAdminNavigation()
    {
        return [
            [
                'link' => '/admin/products/create',
                'name' => 'Add Product'
            ],
            [
                'link' => '/admin/products/view',
                'name' => 'View Products'
            ],
            [
                'link' => '/admin/orders/',
                'name' => 'View orders'
            ],
            [
                'link' => '/',
                'name' => 'Catalog'
            ],
            [
                'link' => '/logout',
                'name' => 'Log Out',
                'class' => 'log_out'
            ]
        ];
    }

    public function getAnonymousNavigation()
    {
        return [
            [
                'link' => '/login',
                'name' => 'Login'
            ],
            [
                'link' => '/',
                'name' => 'Catalog'
            ],
            [
                'link' => '/register',
                'name' => 'Register'
            ]
        ];
    }
}